---
dag_template: simple_dag
dag_name: dataflow_submit_classic_template_job_simple_dag
schedule_interval: '@once'
tasks:
- task_id: dataflow_submit_classic_template_job
  task_type: airflow.providers.google.cloud.operators.dataflow.DataflowTemplatedJobStartOperator
  project_id: project-id
  location: us-central1
  job_name: bigquery_to_cloud_storage
  append_job_name: True
  template: gs://dataflow-templates/latest/Cloud_BigQuery_to_GCS_TensorFlow_Records
  options: {
    "serviceAccountEmail" : "1234-compute@developer.gserviceaccount.com",
    "tempLocation" : "gs://bucket/temp",
    "ipConfiguration" : "WORKER_IP_PRIVATE"
  }
  parameters: {
    "readQuery" : "select * from project_id.dataset.table",
    "outputDirectory" : "gs://bucket/output"
  }
  poll_sleep: 200
  cancel_timeout: 200
  wait_until_finished: True