---
dag_template: "gcs_sensor" 
dag_name: "gcs_sensor_example" 
schedule_interval: "None"
tasks:
- task_id: gcs_sensor_step
  task_type: airflow.providers.google.cloud.sensors.gcs.GCSObjectsWithPrefixExistenceSensor
  bucket: anand-bq-test-2
  prefix: gcs-sensor/
  mode: poke
- task_id: print_file_names
  task_type: airflow.operators.bash.BashOperator
  bash_command: echo {{ ti.xcom_pull(task_ids="gcs_sensor_step") }}
- task_id: gcs_delete_archive_file
  task_type: airflow.providers.google.cloud.operators.gcs.GCSDeleteObjectsOperator
  bucket_name: anand-bq-test-2
  prefix: gcs-sensor/
