---
dag_template: simple_dag 
dag_name: simple_dag_example 
schedule_interval: "None" 
tasks:
- task_id: bash_task_1 
  task_type: airflow.operators.bash.BashOperator
  bash_command: echo "hello 1"
- task_id: bash_task_2 
  task_type: airflow.operators.bash.BashOperator
  bash_command: echo "hello 2"
- task_id: bash_task_3 
  task_type: airflow.operators.bash.BashOperator
  bash_command: echo "hello 3"