---
dag_name: bq_to_sftp_simple_dag
dag_template: simple_dag
schedule_interval: '@hourly'
tasks:
- task_id: bq_query_execute
  task_type: airflow.contrib.operators.bigquery_operator.BigQueryOperator
  sql: 'SELECT * FROM `composer-templates-shared.hmh_demo.covid` WHERE case_reported_date = "2021-08-18"'
  use_legacy_sql: False
  write_disposition: WRITE_TRUNCATE
  allow_large_results: True
  destination_dataset_table: composer-templates-shared.hmh_demo.tmp_covid
- task_id: export_to_gcs
  task_type: airflow.contrib.operators.bigquery_to_gcs.BigQueryToCloudStorageOperator
  source_project_dataset_table: composer-templates-shared.hmh_demo.tmp_covid
  destination_cloud_storage_uris: "gs://hmh_demo/export_files/covid.csv"
  export_format: CSV
  field_delimiter: ','
  print_header: True
- task_id: file_move_gsc_to_sftp
  task_type: airflow.providers.google.cloud.transfers.gcs_to_sftp.GCSToSFTPOperator
  sftp_conn_id: ssh_default
  source_bucket: hmh_demo
  source_object: "export_files/covid.csv"
  destination_path: "sftp_files/"
  move_object: True